import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h3>안녕하세요.</h3>
        <h3>어울리는 프론트 개발자</h3>
        <p>
          <strong>RyuWoong</strong>입니다.
        </p>
      </main>
    </>
  );
}
